import mysql.connector as m
mydatabase=m.connect(host="localhost",user="root",password="12345",database="pythondb1")
cursor=mydatabase.cursor()

query="insertt into dept(dname,loc) values(%s,%s)"
try:
    cursor.execute("insert into dept(dname,loc) values(%s,%s)",['training','Pune'])
	print("done")
    cursor.execute("insertt into dept(dname,loc) values(%s,%s)",['cleaning','Banglore']) #exception arises
	print("Done")
    mydatabase.commit()
except Exception as e:
    print("exception occured\t",e)
    mydatabase.rollback()
	print("changes rollbacked")
print("done")